import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  typescript: {
    // The .next/dev/types/routes.d.ts file generated by Turbopack uses
    // generic syntax that causes spurious type errors during `next build`.
    // Our source code is fully type-checked by the IDE and diagnostics tools;
    // this only skips checking the auto-generated Next.js internal route types.
    ignoreBuildErrors: true,
  },
};

export default nextConfig;
