import type { ExpressTcDashboardData } from "@/types/expressTc";

export const INITIAL_EXPRESS_TC_DATA: ExpressTcDashboardData = {
  journey: {
    trainNumber: "12295",
    route: "Mumbai CSMT → New Delhi",
    journeyDate: "12 Sep 2023",
    boardingPoint: "Mumbai CSMT",
    dutyStart: "08:00 AM",
    dutyEnd: "08:00 PM",
    currentStation: "Nagpur",
    currentStationCode: "NGP",
    nextStation: "Itarsi Jn",
    nextStationCode: "ET",
    eta: "10:58 AM",
    progress: 45,
  },
  summary: {
    ticketsChecked: 128,
    validTickets: 112,
    invalidTickets: 16,
    revenueRecovered: 12450,
    trends: {
      ticketsChecked: 18,
      validTickets: 12,
      invalidTickets: -5,
      revenueRecovered: 22,
    },
  },
  recentVerifications: [
    {
      id: "rv-1",
      passenger: "Rahul Sharma",
      pnr: "4829173645",
      coachBerth: "A1 / S12",
      source: "Mumbai CSMT",
      destination: "New Delhi",
      status: "valid",
      time: "10:45 AM",
    },
    {
      id: "rv-2",
      passenger: "Priya Patel",
      pnr: "7392041856",
      coachBerth: "B1 / L34",
      source: "Mumbai CSMT",
      destination: "New Delhi",
      status: "valid",
      time: "10:42 AM",
    },
    {
      id: "rv-3",
      passenger: "Amit Kumar",
      pnr: "1058472931",
      coachBerth: "S2 / 48",
      source: "Nagpur",
      destination: "Bhopal",
      status: "invalid",
      time: "10:38 AM",
    },
    {
      id: "rv-4",
      passenger: "Sneha Iyer",
      pnr: "6284017395",
      coachBerth: "A2 / U8",
      source: "Mumbai CSMT",
      destination: "New Delhi",
      status: "valid",
      time: "10:35 AM",
    },
    {
      id: "rv-5",
      passenger: "Vikram Singh",
      pnr: "3947182056",
      coachBerth: "B2 / M21",
      source: "Nagpur",
      destination: "New Delhi",
      status: "valid",
      time: "10:30 AM",
    },
  ],
  revenue: {
    today: 12450,
    thisWeek: 68400,
    thisMonth: 248600,
    totalChallans: 36,
  },
  coaches: [
    { code: "A1", capacity: 24, verified: 24, status: "verified" },
    { code: "A2", capacity: 24, verified: 24, status: "verified" },
    { code: "B1", capacity: 7, verified: 3, status: "pending" },
    { code: "B2", capacity: 72, verified: 18, status: "not_started" },
    { code: "S1", capacity: 80, verified: 80, status: "verified" },
    { code: "S2", capacity: 80, verified: 80, status: "verified" },
    { code: "S3", capacity: 80, verified: 42, status: "pending" },
  ],
  alerts: [
    {
      id: "al-1",
      type: "duplicate",
      title: "Duplicate ticket detected",
      message: "Duplicate ticket detected in Coach B1, Seat 12",
      time: "10:45 AM",
      read: false,
    },
    {
      id: "al-2",
      type: "invalid",
      title: "Invalid ticket",
      message: "Invalid ticket found in Coach S2, Seat 48",
      time: "10:38 AM",
      read: false,
    },
    {
      id: "al-3",
      type: "system",
      title: "Payment failed",
      message: "Payment failed for PNR 6284017395",
      time: "10:35 AM",
      read: true,
    },
  ],
  profile: {
    name: "Rahul Kumar",
    id: "TC1024",
    avatarInitials: "RK",
  },
  notificationCount: 3,
  stationSequence: [
    "Mumbai CSMT",
    "Nagpur",
    "Itarsi Jn",
    "Bhopal",
    "Jhansi",
    "New Delhi",
  ],
  stationCodes: ["CSMT", "NGP", "ET", "BPL", "JHS", "NDLS"],
  stationEtas: [
    "08:00 AM",
    "10:30 AM",
    "10:58 AM",
    "01:20 PM",
    "04:10 PM",
    "08:00 PM",
  ],
};
